stages:
- stage: Build
  jobs:
  - job: Build
    pool: 'Hosted VS2017'
    steps:
    - script: echo 'Build'

- stage: PPE
  jobs:
  - job: Test
    pool: 'Hosted VS2017'
    steps:
    - script: echo 'Hosted'
    - task: NuGetToolInstaller@0
  - deployment: DeployPPE
    environment: ankhokha
    pool: 'Hosted VS2017'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
